### ISSUE TITLE
Invalid JWT Builder ID

### ISSUE THREAD

**Issue by Raunak-S** [IBMStockTrader/looper#4]
Error when running Looper:
`[err] com.ibm.websphere.security.jwt.InvalidBuilderException: CWWKS6008E: The specified JSON Web Token (JWT) builder ID [myBuilder] is not valid. Verify that a JWT builder with the specified ID is configured.`

John figured out problem is with `server.xml` and updating an old JWT Builder ID.

**Comment by jwalcorn** [comment]
Fixed this last week.  the "id" specified in the code and in the server.xml were mismatched for the jwtBuilder.  Thanks for finding/reporting this!
